<?php

declare(strict_types=1);

namespace App\Domain\Inventory\Services;

use App\Domain\Inventory\Models\StockAdjustment;
use App\Domain\Inventory\Models\StockAuditItem;
use App\Domain\Inventory\Models\StockAuditSession;
use App\Domain\Inventory\Models\Warehouse;
use App\Domain\Product\Models\ProductStock;
use App\Models\SiteSetting;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use RuntimeException;

class CycleCountService
{
    public const DEFAULT_SAMPLE_SIZE = 20;

    public const DEFAULT_FREQUENCY = 'weekly';

    /**
     * @return array<string, mixed>
     */
    public function getSettings(): array
    {
        return [
            'auto_generate_enabled' => filter_var(SiteSetting::get('cycle_count_auto_generate_enabled', 'false'), FILTER_VALIDATE_BOOLEAN),
            'frequency' => (string) SiteSetting::get('cycle_count_frequency', self::DEFAULT_FREQUENCY),
            'sample_size' => (int) SiteSetting::get('cycle_count_sample_size', self::DEFAULT_SAMPLE_SIZE),
            'auto_create_adjustments' => filter_var(SiteSetting::get('cycle_count_auto_create_adjustments', 'true'), FILTER_VALIDATE_BOOLEAN),
        ];
    }

    /**
     * @param  array<string, mixed>  $data
     */
    public function updateSettings(array $data): void
    {
        if (array_key_exists('auto_generate_enabled', $data)) {
            SiteSetting::set('cycle_count_auto_generate_enabled', $data['auto_generate_enabled'] ? 'true' : 'false');
        }
        if (array_key_exists('frequency', $data)) {
            SiteSetting::set('cycle_count_frequency', $data['frequency']);
        }
        if (array_key_exists('sample_size', $data)) {
            SiteSetting::set('cycle_count_sample_size', (string) $data['sample_size']);
        }
        if (array_key_exists('auto_create_adjustments', $data)) {
            SiteSetting::set('cycle_count_auto_create_adjustments', $data['auto_create_adjustments'] ? 'true' : 'false');
        }
    }

    /**
     * Generate scheduled cycle counts for warehouses that are due, based on
     * the configured frequency. Called by the scheduled console command.
     *
     * @return array{generated: int, skipped: int}
     */
    public function generateScheduled(): array
    {
        $settings = $this->getSettings();

        if (! $settings['auto_generate_enabled']) {
            return ['generated' => 0, 'skipped' => 0];
        }

        $generated = 0;
        $skipped = 0;

        Warehouse::where('is_active', true)->each(function (Warehouse $warehouse) use ($settings, &$generated, &$skipped) {
            if ($this->isDue($warehouse->id, $settings['frequency'])) {
                $this->createSession($warehouse->id, $settings['sample_size'], null, true);
                $generated++;
            } else {
                $skipped++;
            }
        });

        return ['generated' => $generated, 'skipped' => $skipped];
    }

    private function isDue(int $warehouseId, string $frequency): bool
    {
        $lastSession = StockAuditSession::where('warehouse_id', $warehouseId)
            ->where('auto_generated', true)
            ->latest('created_at')
            ->first();

        if (! $lastSession) {
            return true;
        }

        $intervalDays = match ($frequency) {
            'daily' => 1,
            'monthly' => 30,
            default => 7,
        };

        return $lastSession->created_at->lte(Carbon::now()->subDays($intervalDays));
    }

    /**
     * Create a new cycle count session with a random sample of products
     * that currently have stock in the given warehouse.
     */
    public function createSession(int $warehouseId, int $sampleSize, ?int $createdBy = null, bool $autoGenerated = false): StockAuditSession
    {
        return DB::transaction(function () use ($warehouseId, $sampleSize, $createdBy, $autoGenerated) {
            $session = StockAuditSession::create([
                'warehouse_id' => $warehouseId,
                'name' => ($autoGenerated ? 'Scheduled' : 'Manual').' Cycle Count — '.now()->format('M j, Y'),
                'status' => StockAuditSession::STATUS_OPEN,
                'started_by' => $createdBy,
                'started_at' => now(),
                'auto_generated' => $autoGenerated,
            ]);

            $stocks = ProductStock::with('product')
                ->where('warehouse_id', $warehouseId)
                ->where('current_stock', '>', 0)
                ->whereHas('product', fn ($q) => $q->where('is_active', true))
                ->inRandomOrder()
                ->limit($sampleSize)
                ->get();

            foreach ($stocks as $stock) {
                StockAuditItem::create([
                    'session_id' => $session->id,
                    'product_id' => $stock->product_id,
                    'variant_id' => $stock->variant_id,
                    'location_id' => $stock->location_id,
                    'system_qty' => $stock->current_stock,
                    'status' => StockAuditItem::STATUS_PENDING,
                ]);
            }

            return $session->fresh();
        });
    }

    /**
     * @return array<string, mixed>
     */
    public function getDashboard(): array
    {
        $sessions = StockAuditSession::with('warehouse')
            ->withCount([
                'items',
                'items as counted_items_count' => fn ($q) => $q->where('status', StockAuditItem::STATUS_COUNTED),
                'items as variance_items_count' => fn ($q) => $q->where('status', StockAuditItem::STATUS_COUNTED)->where('variance', '!=', 0),
            ])
            ->latest('created_at')
            ->limit(50)
            ->get()
            ->map(fn (StockAuditSession $s) => $this->flattenSession($s));

        return [
            'sessions' => $sessions,
            'summary' => [
                'open_sessions' => StockAuditSession::whereIn('status', [StockAuditSession::STATUS_OPEN, StockAuditSession::STATUS_COUNTING])->count(),
                'finalized_sessions' => StockAuditSession::where('status', StockAuditSession::STATUS_FINALIZED)->count(),
                'total_variance_items' => StockAuditItem::where('status', StockAuditItem::STATUS_COUNTED)->where('variance', '!=', 0)->count(),
                'accuracy_rate' => $this->accuracyRate(),
            ],
            'settings' => $this->getSettings(),
            'warehouses' => Warehouse::where('is_active', true)->orderBy('name')->get(['id', 'name', 'code']),
        ];
    }

    private function accuracyRate(): float
    {
        $counted = StockAuditItem::where('status', StockAuditItem::STATUS_COUNTED)->count();
        if ($counted === 0) {
            return 100.0;
        }
        $accurate = StockAuditItem::where('status', StockAuditItem::STATUS_COUNTED)->where('variance', 0)->count();

        return round($accurate / $counted * 100, 1);
    }

    private function flattenSession(StockAuditSession $s): array
    {
        return [
            'id' => $s->id,
            'name' => $s->name,
            'warehouse' => $s->warehouse?->name ?? 'Unknown',
            'warehouse_id' => $s->warehouse_id,
            'status' => $s->status,
            'auto_generated' => (bool) $s->auto_generated,
            'total_items' => $s->items_count ?? 0,
            'counted_items' => $s->counted_items_count ?? 0,
            'variance_items' => $s->variance_items_count ?? 0,
            'started_at' => $s->started_at?->toIso8601String(),
            'finalized_at' => $s->finalized_at?->toIso8601String(),
            'created_at' => $s->created_at?->toIso8601String(),
        ];
    }

    /**
     * @return array<string, mixed>
     */
    public function getSession(int $sessionId): array
    {
        $session = StockAuditSession::with('warehouse', 'startedBy', 'finalizedBy')->findOrFail($sessionId);

        $items = StockAuditItem::with(['product:id,sku,name,cost_price', 'location:id,code,name'])
            ->where('session_id', $sessionId)
            ->get()
            ->map(function (StockAuditItem $item) {
                $unitCost = (float) ($item->product?->cost_price ?? 0);
                $varianceValue = $item->variance !== null ? round($item->variance * $unitCost, 2) : null;
                $variancePct = ($item->variance !== null && $item->system_qty > 0)
                    ? round($item->variance / $item->system_qty * 100, 1)
                    : null;

                return [
                    'id' => $item->id,
                    'product_id' => $item->product_id,
                    'sku' => $item->product?->sku ?? '—',
                    'name' => $item->product?->name ?? 'Unknown',
                    'location' => $item->location?->code ?? $item->location?->name,
                    'system_qty' => $item->system_qty,
                    'counted_qty' => $item->counted_qty,
                    'variance' => $item->variance,
                    'variance_pct' => $variancePct,
                    'unit_cost' => $unitCost,
                    'variance_value' => $varianceValue,
                    'status' => $item->status,
                    'counted_at' => $item->counted_at?->toIso8601String(),
                    'adjustment_id' => $item->adjustment_id,
                ];
            });

        return [
            'session' => [
                'id' => $session->id,
                'name' => $session->name,
                'warehouse' => $session->warehouse?->name ?? 'Unknown',
                'warehouse_id' => $session->warehouse_id,
                'status' => $session->status,
                'started_by' => $session->startedBy?->name,
                'finalized_by' => $session->finalizedBy?->name,
                'started_at' => $session->started_at?->toIso8601String(),
                'finalized_at' => $session->finalized_at?->toIso8601String(),
                'notes' => $session->notes,
            ],
            'items' => $items,
            'summary' => [
                'total_items' => $items->count(),
                'counted_items' => $items->where('status', StockAuditItem::STATUS_COUNTED)->count(),
                'variance_items' => $items->filter(fn ($i) => $i['variance'] !== null && $i['variance'] !== 0)->count(),
                'total_variance_qty' => $items->sum('variance'),
                'total_variance_value' => round((float) $items->sum('variance_value'), 2),
            ],
        ];
    }

    /**
     * Record a counted quantity for a cycle count item.
     */
    public function recordCount(int $itemId, int $countedQty, int $userId, ?string $notes = null): StockAuditItem
    {
        $item = StockAuditItem::findOrFail($itemId);

        $item->update([
            'counted_qty' => $countedQty,
            'variance' => $countedQty - $item->system_qty,
            'status' => StockAuditItem::STATUS_COUNTED,
            'counted_by' => $userId,
            'counted_at' => now(),
            'notes' => $notes,
        ]);

        $session = $item->session;
        if ($session && $session->status === StockAuditSession::STATUS_OPEN) {
            $session->update(['status' => StockAuditSession::STATUS_COUNTING]);
        }

        return $item->fresh();
    }

    /**
     * Skip an item (not counted).
     */
    public function skipItem(int $itemId): StockAuditItem
    {
        $item = StockAuditItem::findOrFail($itemId);
        $item->update(['status' => StockAuditItem::STATUS_SKIPPED]);

        return $item->fresh();
    }

    /**
     * Finalize a session. Optionally auto-creates pending StockAdjustment
     * records for items with a non-zero variance, reusing the existing
     * adjustment approval workflow.
     *
     * @return array{session: StockAuditSession, adjustments_created: int}
     */
    public function finalizeSession(int $sessionId, int $userId): array
    {
        $session = StockAuditSession::findOrFail($sessionId);

        if ($session->status === StockAuditSession::STATUS_FINALIZED) {
            throw new RuntimeException('Cycle count session is already finalized.');
        }

        $settings = $this->getSettings();
        $adjustmentsCreated = 0;

        DB::transaction(function () use ($session, $userId, $settings, &$adjustmentsCreated) {
            $session->update([
                'status' => StockAuditSession::STATUS_FINALIZED,
                'finalized_by' => $userId,
                'finalized_at' => now(),
            ]);

            if (! $settings['auto_create_adjustments']) {
                return;
            }

            $varianceItems = StockAuditItem::where('session_id', $session->id)
                ->where('status', StockAuditItem::STATUS_COUNTED)
                ->where('variance', '!=', 0)
                ->whereNull('adjustment_id')
                ->get();

            foreach ($varianceItems as $item) {
                $adjustment = StockAdjustment::create([
                    'product_id' => $item->product_id,
                    'variant_id' => $item->variant_id,
                    'warehouse_id' => $session->warehouse_id,
                    'location_id' => $item->location_id,
                    'reason_code' => 'CYCLE_COUNT',
                    'reason_notes' => "Cycle count variance from session #{$session->id} ({$session->name})",
                    'quantity_before' => $item->system_qty,
                    'quantity_after' => $item->counted_qty,
                    'variance' => $item->variance,
                    'status' => 'PENDING',
                    'submitted_by' => $userId,
                ]);

                $item->update(['adjustment_id' => $adjustment->id]);
                $adjustmentsCreated++;
            }
        });

        return ['session' => $session->fresh(), 'adjustments_created' => $adjustmentsCreated];
    }

    public function cancelSession(int $sessionId): StockAuditSession
    {
        $session = StockAuditSession::findOrFail($sessionId);

        if ($session->status === StockAuditSession::STATUS_FINALIZED) {
            throw new RuntimeException('Cannot cancel a finalized session.');
        }

        $session->update(['status' => StockAuditSession::STATUS_CANCELLED]);

        return $session->fresh();
    }

    /**
     * Aggregated variance report across finalized sessions within a date range.
     *
     * @return array<string, mixed>
     */
    public function varianceReport(?string $from = null, ?string $to = null, ?int $warehouseId = null): array
    {
        $query = StockAuditItem::with(['product:id,sku,name,cost_price', 'session:id,warehouse_id,name,finalized_at'])
            ->where('status', StockAuditItem::STATUS_COUNTED)
            ->whereHas('session', function ($q) use ($from, $to, $warehouseId) {
                $q->where('status', StockAuditSession::STATUS_FINALIZED)
                    ->when($from, fn ($qq, $d) => $qq->whereDate('finalized_at', '>=', $d))
                    ->when($to, fn ($qq, $d) => $qq->whereDate('finalized_at', '<=', $d))
                    ->when($warehouseId, fn ($qq, $wid) => $qq->where('warehouse_id', $wid));
            });

        $items = $query->get();

        $rows = $items->map(function (StockAuditItem $item) {
            $unitCost = (float) ($item->product?->cost_price ?? 0);

            return [
                'session_id' => $item->session_id,
                'session_name' => $item->session?->name,
                'sku' => $item->product?->sku ?? '—',
                'name' => $item->product?->name ?? 'Unknown',
                'system_qty' => $item->system_qty,
                'counted_qty' => $item->counted_qty,
                'variance' => $item->variance,
                'variance_value' => round(($item->variance ?? 0) * $unitCost, 2),
                'finalized_at' => $item->session?->finalized_at,
            ];
        });

        return [
            'rows' => $rows->values(),
            'summary' => [
                'total_counted' => $rows->count(),
                'accurate_count' => $rows->where('variance', 0)->count(),
                'variance_count' => $rows->where('variance', '!=', 0)->count(),
                'total_shortage_qty' => (int) $rows->filter(fn ($r) => $r['variance'] < 0)->sum('variance'),
                'total_overage_qty' => (int) $rows->filter(fn ($r) => $r['variance'] > 0)->sum('variance'),
                'total_variance_value' => round((float) $rows->sum('variance_value'), 2),
                'accuracy_rate' => $rows->count() > 0 ? round($rows->where('variance', 0)->count() / $rows->count() * 100, 1) : 100.0,
            ],
        ];
    }
}
