apiVersion: v1
kind: Service
metadata:
  name: warehouseops-staging
  namespace: warehouseops-staging
  labels:
    app: warehouseops
    environment: staging
spec:
  type: ClusterIP
  selector:
    app: warehouseops
    environment: staging
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
